In [1]:
# -*- coding: utf-8 -*-

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import numpy as np
!pip install geopandas
import geopandas as gpd
import folium

     |████████████████████████████████| 972kB 5.9MB/s 
     |████████████████████████████████| 14.8MB 295kB/s 
     |████████████████████████████████| 6.5MB 47.7MB/s 


# 1. 전유부

In [3]:
전유부 = pd.read_csv('/content/drive/Shareddrives/세종시_프로젝트/data/1.세종시_전유부.csv', encoding='CP949')
전유부.head(2)

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (11) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


순번                      대지위치  시군구코드  법정동코드  ...      동명칭  호명칭  층구분코드명 층번호
0   1  세종특별자치시  반곡동 4121-1002번지  36110  10100  ...  주건축물제1동  616      지상   6
1   2  세종특별자치시  반곡동 4121-1002번지  36110  10100  ...  주건축물제1동  624      지상   6

[2 rows x 16 columns]

## 변수 삭제

- 대지위치 : 시군구코드, 법정동코드, 번, 지 로 알 수 있음
- 대장구분코드명 : 모두 '집합'으로 같음
- 건물명 : 대지위치와 같은 이유
- 동명칭, 호명칭, 층번호 : 필요없음
- 층구분코드명 : 필요없을듯

In [4]:
전유부 = 전유부.drop(['대지위치','대장구분코드명','건물명','동명칭','호명칭','층구분코드명','층번호'], axis=1)
전유부.head(2)

순번  시군구코드  법정동코드  대지구분코드     번     지 특수지명   블록   로트
0   1  36110  10100       1  4121  1002  NaN  NaN  NaN
1   2  36110  10100       1  4121  1002  NaN  NaN  NaN

## 결측값 처리

In [5]:
전유부.isnull().sum()

순번            0
시군구코드         0
법정동코드         0
대지구분코드        0
번             0
지             0
특수지명      15033
블록        15212
로트        38935
dtype: int64

In [6]:
전유부['특수지명'].unique()

array([nan, '4-1생활권 C1-6블럭', '4-1생활권', '행복도시 4-1생활권', '행정중심복합도시 4-1생활권',
       '행정중심복합도시4-1생활권', '3-3 생활권', '3-3생활권 C13-2', '3-3생활권',
       '세종특별자치시 3-3생활권', '행복중심복합도시3-3생활권', '행정중심복합도시 3-3생활권', '3-2생활권',
       '행정중심복합도시 3-2생활권', '행정중심복합도시3-2생활권', '행정중심복합도시', '3-1생활권',
       '행정중심복합도시 3-1생활권', '행정중심복합도시3-1생활권', '2-3생활권'], dtype=object)

In [7]:
전유부['블록'].unique()

array([nan, 'C 3-1', 'C 4-', 'C1-1BL', 'C1-4', 'C4-7블록', 'L2블록', 'M1블록',
       'M3블록', 'c4-6', 'C2-1', 'C2-2블록', 'L4블록', 'M2블록', 'L3블록', 'C14',
       'C10-2', 'C15', 'C16-1', 'C16-2BL', 'C5-4BL', 'C6', 'C8-1',
       'C8-2블록', 'C5-3블록', 'C12', 'C13-1', 'C13-3블럭', 'C16', 'M4블록',
       'M6블록', 'H1블록', 'M1', 'M3블럭', 'L1블럭', 'M5블록', '3-2생활권', 'M2BL',
       'M3BL', 'M4블럭', 'RC1-3'], dtype=object)

In [8]:
전유부['로트'].unique()

array([nan, '5', '1', '2', '-1', '-4', 'M4블록'], dtype=object)

### 결측 변수 삭제

- 블록 : 결측치가 많고, 특수지명과 일부 겹치는 것으로 보여 삭제
- 로트 : 대부분이 결측치

In [9]:
전유부 = 전유부.drop(['블록','로트'], axis=1)
전유부.head(2)

순번  시군구코드  법정동코드  대지구분코드     번     지 특수지명
0   1  36110  10100       1  4121  1002  NaN
1   2  36110  10100       1  4121  1002  NaN

### 결측 변수 대체 (임의)

In [10]:
전유부['특수지명'].mode()  ### 최빈값

0    행정중심복합도시 3-3생활권
dtype: object

특수지명 변수의 결측값을 최빈값으로 대체. 임의로 대체한 것이므로 나중에 상의 후 변경

In [11]:
전유부['특수지명'] = 전유부['특수지명'].fillna('행정중심복합도시 3-3생활권')
전유부.head(2)

순번  시군구코드  법정동코드  대지구분코드     번     지             특수지명
0   1  36110  10100       1  4121  1002  행정중심복합도시 3-3생활권
1   2  36110  10100       1  4121  1002  행정중심복합도시 3-3생활권

In [12]:
전유부.isnull().sum()

순번        0
시군구코드     0
법정동코드     0
대지구분코드    0
번         0
지         0
특수지명      0
dtype: int64

# 2. 표제부

In [13]:
표제부 = pd.read_csv('/content/drive/Shareddrives/세종시_프로젝트/data/2.세종시_표제부.csv', encoding='CP949')
표제부.head(2)

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (10,13) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


순번                   대지위치  시군구코드  ...  세대수(세대)   사용승인일  Unnamed: 15
0   1  세종특별자치시  반곡동 146-75번지  36110  ...        0  1977.0          NaN
1   2  세종특별자치시  반곡동 146-79번지  36110  ...        0  1999.0          NaN

[2 rows x 16 columns]

## 변수 삭제

- 대지위치 : 시군구코드, 법정동코드, 번, 지 로 알 수 있음
- 대장구분코드명 : 의미 없어보여 임의로 삭제 -- 상의 후 결정
- 동명칭 : 필요없음
- 건물명 : 대지위치와 같은 이유
- Unnamed: 15 : 의미 알 수 없고 값이 한가지거나 결측값인 변수로, 삭제

In [14]:
표제부 = 표제부.drop(['대지위치','대장구분코드명','건물명','동명칭'], axis=1)
표제부.head(2)

순번  시군구코드  법정동코드  대지구분코드    번  ...   구조코드명    주용도코드명 세대수(세대)   사용승인일 Unnamed: 15
0   1  36110  10100       1  146  ...    벽돌구조      단독주택       0  1977.0         NaN
1   2  36110  10100       1  146  ...  강파이프구조  동.식물관련시설       0  1999.0         NaN

[2 rows x 12 columns]

In [15]:
표제부['Unnamed: 15'].unique()

array([      nan, 20130823.])

In [16]:
표제부['Unnamed: 15'].isnull().sum()

36728

In [17]:
표제부 = 표제부.drop(['Unnamed: 15'], axis=1)
표제부.head(2)

순번  시군구코드  법정동코드  대지구분코드    번   지  연면적(㎡)   구조코드명    주용도코드명 세대수(세대)   사용승인일
0   1  36110  10100       1  146  75  135.24    벽돌구조      단독주택       0  1977.0
1   2  36110  10100       1  146  79     576  강파이프구조  동.식물관련시설       0  1999.0

## 결측값 처리

In [18]:
표제부.isnull().sum()

순번            0
시군구코드         0
법정동코드         0
대지구분코드        0
번             0
지             0
연면적(㎡)        0
구조코드명         9
주용도코드명       12
세대수(세대)       0
사용승인일      1212
dtype: int64

### 결측값 대체

- 구조코드명, 주용도코드명 : 최빈값으로 대체

In [19]:
print(표제부['구조코드명'].mode())
print(표제부['주용도코드명'].mode())

0    철근콘크리트구조
dtype: object
0    단독주택
dtype: object


In [20]:
표제부['구조코드명'] = 표제부['구조코드명'].fillna('철근콘크리트구조')
표제부['주용도코드명'] = 표제부['주용도코드명'].fillna('단독주택')
표제부.isnull().sum()

순번            0
시군구코드         0
법정동코드         0
대지구분코드        0
번             0
지             0
연면적(㎡)        0
구조코드명         0
주용도코드명        0
세대수(세대)       0
사용승인일      1212
dtype: int64

- 사용승인일 : 0으로 대체 (임의)

In [21]:
표제부['사용승인일'] = 표제부['사용승인일'].fillna(0)
표제부.isnull().sum()

순번         0
시군구코드      0
법정동코드      0
대지구분코드     0
번          0
지          0
연면적(㎡)     0
구조코드명      0
주용도코드명     0
세대수(세대)    0
사용승인일      0
dtype: int64

In [22]:
표제부.head(2)

순번  시군구코드  법정동코드  대지구분코드    번   지  연면적(㎡)   구조코드명    주용도코드명 세대수(세대)   사용승인일
0   1  36110  10100       1  146  75  135.24    벽돌구조      단독주택       0  1977.0
1   2  36110  10100       1  146  79     576  강파이프구조  동.식물관련시설       0  1999.0

## 데이터 형식 변환

- 사용승인일 : 년도만 있으면 월일 0101로 임의 설정
- 법정동코드 : 세자리수로 뒤의 2자리 삭제. 임의 설정이므로 나중에 상의 후 변경



In [23]:
표제부 = 표제부.astype({'사용승인일':int})  ### 소수점 버림
표제부 = 표제부.astype({'사용승인일':str})
표제부.head()

순번  시군구코드  법정동코드  대지구분코드    번  ...   연면적(㎡)     구조코드명    주용도코드명 세대수(세대)     사용승인일
0   1  36110  10100       1  146  ...   135.24      벽돌구조      단독주택       0      1977
1   2  36110  10100       1  146  ...      576    강파이프구조  동.식물관련시설       0      1999
2   3  36110  10100       1  146  ...      336    강파이프구조  동.식물관련시설       0  20041223
3   4  36110  10100       1  146  ...   127.19    강파이프구조      창고시설       0  19950726
4   5  36110  10100       1  180  ...  2697.74  철근콘크리트구조    교육연구시설       0  20190228

[5 rows x 11 columns]

In [24]:
표제부['사용승인일'] = 표제부['사용승인일'].apply(lambda x: x+'0101' if len(x)==4 else x)
표제부.head()

순번  시군구코드  법정동코드  대지구분코드    번  ...   연면적(㎡)     구조코드명    주용도코드명 세대수(세대)     사용승인일
0   1  36110  10100       1  146  ...   135.24      벽돌구조      단독주택       0  19770101
1   2  36110  10100       1  146  ...      576    강파이프구조  동.식물관련시설       0  19990101
2   3  36110  10100       1  146  ...      336    강파이프구조  동.식물관련시설       0  20041223
3   4  36110  10100       1  146  ...   127.19    강파이프구조      창고시설       0  19950726
4   5  36110  10100       1  180  ...  2697.74  철근콘크리트구조    교육연구시설       0  20190228

[5 rows x 11 columns]

In [25]:
표제부.describe()

순번    시군구코드  ...             번             지
count  36729.000000  36729.0  ...  36729.000000  36729.000000
mean   18365.000000  36110.0  ...    310.429388      6.002968
std    10602.893355      0.0  ...    306.729458     48.020151
min        1.000000  36110.0  ...      0.000000      0.000000
25%     9183.000000  36110.0  ...     90.000000      0.000000
50%    18365.000000  36110.0  ...    226.000000      1.000000
75%    27547.000000  36110.0  ...    436.000000      5.000000
max    36729.000000  36110.0  ...   5477.000000   7007.000000

[8 rows x 6 columns]

In [26]:
표제부['법정동코드'] = 표제부['법정동코드'].astype(str).str.slice(0,3)
표제부.head(2)

순번  시군구코드 법정동코드  대지구분코드    번   지  연면적(㎡)   구조코드명    주용도코드명 세대수(세대)     사용승인일
0   1  36110   101       1  146  75  135.24    벽돌구조      단독주택       0  19770101
1   2  36110   101       1  146  79     576  강파이프구조  동.식물관련시설       0  19990101

# 3~10. 실거래가 데이터

In [59]:
아파트_매매 = pd.read_csv('/content/drive/Shareddrives/세종시_프로젝트/data/3.세종시_아파트(매매)_실거래가.csv', encoding= 'CP949')
연립다세대_매매 = pd.read_csv('/content/drive/Shareddrives/세종시_프로젝트/data/4.세종시_연립다세대(매매)_실거래가.csv', encoding='CP949')
단독다가구_매매 = pd.read_csv('/content/drive/Shareddrives/세종시_프로젝트/data/5.세종시_단독다가구(매매)_실거래가.csv', encoding='CP949')
오피스텔_매매 = pd.read_csv('/content/drive/Shareddrives/세종시_프로젝트/data/6.세종시_오피스텔(매매)_실거래가.csv', encoding='CP949')
아파트_전월세 = pd.read_csv('/content/drive/Shareddrives/세종시_프로젝트/data/7.세종시_아파트(전월세)_실거래가.csv', encoding='CP949')
연립다세대_전월세 = pd.read_csv('/content/drive/Shareddrives/세종시_프로젝트/data/8.세종시_연립다세대(전월세)_실거래가.csv', encoding='CP949')
단독다가구_전월세 = pd.read_csv('/content/drive/Shareddrives/세종시_프로젝트/data/9.세종시_단독다가구(전월세)_실거래가.csv', encoding='CP949')
오피스텔_전월세 = pd.read_csv('/content/drive/Shareddrives/세종시_프로젝트/data/10.세종시_오피스텔(전월세)_실거래가.csv', encoding='CP949')

In [60]:
아파트_매매.head(2)

계약년월  계약일          시군구   본번  ...  전용면적(㎡) 거래금액(만원)  층  건축년도
0  201701    1  세종특별자치시 보람동  628  ...  16.9849     8600  7  2016
1  201701    1  세종특별자치시 종촌동  683  ...  59.8652    27300  7  2014

[2 rows x 10 columns]

In [61]:
print(list(아파트_매매.columns))
print(list(연립다세대_매매.columns))
print(list(단독다가구_매매.columns))
print(list(오피스텔_매매.columns))

['계약년월', '계약일', '시군구', '본번', '부번', '단지명', '전용면적(㎡)', '거래금액(만원)', '층', '건축년도']
['계약년월', '계약일', '시군구', '본번', '부번', '건물명', '전용면적(㎡)', '대지권면적(㎡)', '거래금액(만원)', '층', '건축년도']
['계약년월', '계약일', '시군구', '주택유형', '도로조건', '연면적(㎡)', '대지면적(㎡)', '거래금액(만원)', '건축년도']
['계약년월', '계약일', '시군구', '본번', '부번', '단지명', '전용면적(㎡)', '거래금액(만원)', '층', '건축년도']


## 3~6. 매매 데이터

- 주택유형 변수 추가 : 아파트 / 연립다세대 / 단독 / 다가구 / 오피스텔
- 계약날짜 변수 추가 : 계약년월 + 계약일 
- 계약년월, 계약일 변수 삭제
- 단독다가구의 대지면적 변수를 전용면적으로 rename

- 우선 단독다가구_매매의 건축년도 결측 대체

In [62]:
단독다가구_매매.isnull().sum()

계약년월        0
계약일         0
시군구         0
주택유형        0
도로조건        0
연면적(㎡)      0
대지면적(㎡)     0
거래금액(만원)    0
건축년도        4
dtype: int64

In [63]:
단독다가구_매매['건축년도'].mode()

0    2013.0
dtype: float64

In [64]:
단독다가구_매매['건축년도'] = 단독다가구_매매['건축년도'].fillna(2013)
단독다가구_매매['건축년도'].isnull().sum()

0

In [65]:
아파트_매매['주택유형'] = '아파트'
연립다세대_매매['주택유형'] = '연립다세대'
오피스텔_매매['주택유형'] = '오피스텔'
아파트_매매.head(2)

계약년월  계약일          시군구   본번  부번  ...  전용면적(㎡)  거래금액(만원)  층  건축년도  주택유형
0  201701    1  세종특별자치시 보람동  628   2  ...  16.9849      8600  7  2016   아파트
1  201701    1  세종특별자치시 종촌동  683   0  ...  59.8652     27300  7  2014   아파트

[2 rows x 11 columns]

In [66]:
def 계약날짜_추가(data):
    data['계약년월'] = data['계약년월'].astype(str)
    data['계약일'] = data['계약일'].astype('int64').apply(lambda x: "{:0>2d}".format(x))
    data['계약날짜'] = data[['계약년월','계약일']].apply(lambda x: ''.join(x), axis=1)

    data = data.drop(['계약년월','계약일'], axis=1)
    return data

아파트_매매 = 계약날짜_추가(아파트_매매)
연립다세대_매매 = 계약날짜_추가(연립다세대_매매)
단독다가구_매매 = 계약날짜_추가(단독다가구_매매)
오피스텔_매매 = 계약날짜_추가(오피스텔_매매)
아파트_매매.head(2)

시군구   본번  부번                단지명  ...  층  건축년도  주택유형      계약날짜
0  세종특별자치시 보람동  628   2       스타힐타워Ⅰ(C2-3)  ...  7  2016   아파트  20170101
1  세종특별자치시 종촌동  683   0  가재마을2단지(호반베르디움3차)  ...  7  2014   아파트  20170101

[2 rows x 10 columns]

In [67]:
단독다가구_매매 = 단독다가구_매매.rename(columns={'대지면적(㎡)':'전용면적(㎡)'})
단독다가구_매매.head(2)

시군구 주택유형  도로조건  연면적(㎡)  전용면적(㎡)  거래금액(만원)    건축년도      계약날짜
0   세종특별자치시 전의면 다방리   단독  8m미만   67.32    294.0      2000  1991.0  20170102
1  세종특별자치시 조치원읍 서창리   단독  8m미만  581.25    415.0     54500  1997.0  20170104

In [68]:
매매_실거래가 = pd.concat([아파트_매매, 연립다세대_매매, 단독다가구_매매, 오피스텔_매매])
매매_실거래가.tail(2)

시군구 본번   부번       단지명  ...  건물명 대지권면적(㎡)  도로조건  연면적(㎡)
266  세종특별자치시 어진동  0  0.0    푸르지오시티  ...  NaN      NaN   NaN     NaN
267  세종특별자치시 어진동  0  0.0  2차푸르지오시티  ...  NaN      NaN   NaN     NaN

[2 rows x 14 columns]

## 7~10. 전월세 데이터

- 결측치 대체

In [69]:
print(list(아파트_전월세.columns))
print(list(연립다세대_전월세.columns))
print(list(단독다가구_전월세.columns))
print(list(오피스텔_전월세.columns))

['계약년월', '계약일', '시군구', '본번', '부번', '단지명', '전월세구분', '전용면적(㎡)', '보증금(만원)', '월세(만원)', '층', '건축년도']
['계약년월', '계약일', '시군구', '본번', '부번', '건물명', '전월세구분', '전용면적(㎡)', '보증금(만원)', '월세(만원)', '층', '건축년도']
['계약년월', '계약일', '시군구', '도로조건', '계약면적(㎡)', '전월세구분', '보증금(만원)', '월세(만원)', '건축년도']
['계약년월', '계약일', '시군구', '본번', '부번', '단지명', '전월세구분', '전용면적(㎡)', '보증금(만원)', '월세(만원)', '층', '건축년도']


In [70]:
단독다가구_전월세.isnull().sum()

계약년월         0
계약일          0
시군구          0
도로조건         0
계약면적(㎡)      0
전월세구분        0
보증금(만원)      0
월세(만원)       0
건축년도       210
dtype: int64

In [72]:
단독다가구_전월세['건축년도'].mode()

0    2013.0
dtype: float64

In [73]:
단독다가구_전월세['건축년도'] = 단독다가구_전월세['건축년도'].fillna(2013)
단독다가구_전월세['건축년도'].isnull().sum()

0

In [74]:
아파트_전월세['주택유형'] = '아파트'
연립다세대_전월세['주택유형'] = '연립다세대'
오피스텔_전월세['주택유형'] = '오피스텔'

아파트_전월세 = 계약날짜_추가(아파트_전월세)
연립다세대_전월세 = 계약날짜_추가(연립다세대_전월세)
단독다가구_전월세 = 계약날짜_추가(단독다가구_전월세)
오피스텔_전월세 = 계약날짜_추가(오피스텔_전월세)

전월세_실거래가 = pd.concat([아파트_전월세, 연립다세대_전월세, 단독다가구_전월세, 오피스텔_전월세])
전월세_실거래가.tail(2)

시군구   본번   부번      단지명 전월세구분  ...  주택유형      계약날짜  건물명  도로조건  계약면적(㎡)
1209  세종특별자치시 도담동  246  5.0  세종한신휴시티    월세  ...  오피스텔  20201006  NaN   NaN      NaN
1210  세종특별자치시 나성동  713  0.0   세진이너스빌    월세  ...  오피스텔  20201021  NaN   NaN      NaN

[2 rows x 15 columns]